# Generated by Django 5.0.1 on 2024-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_anonym', models.CharField(max_length=255, null=True)),
                ('nombre_enfants', models.IntegerField(null=True)),
                ('categorie_socioprofessionnelle', models.CharField(max_length=255)),
                ('prix_panier_client', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('collecte_achat', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecte', models.IntegerField()),
                ('categorie_article', models.CharField(max_length=255)),
                ('prix_article', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
